### ISSUE TITLE
Webpack Dev Middleware error on production environment

### ISSUE THREAD

**Issue by khoait** [ajtowf/aspnetcore-angular#2]
Hi Ajden,

I'm following your course "Using ASP.NET Core to Build Single-page Applications" on PluralSight. I've successfully created build definition and release definition. But the website loads with error:

```
An error occurred while starting the application.

Exception: Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (D:\local\Temp\tmp89CC.tmp:83:19)
at __webpack_require__ (D:\local\Temp\tmp89CC.tmp:20:30)
at createWebpackDevServer (D:\local\Temp\tmp89CC.tmp:62:26)
at D:\local\Temp\tmp8A6A.tmp:113:19
at IncomingMessage.<anonymous> (D:\local\Temp\tmp8A6A.tmp:132:38)
at emitNone (events.js:86:13)
Current directory is: D:\home\site\wwwroot
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()
```

It failed to load "Webpack dev middleware". Looks like it was built for development environment which maybe because of hosting.json.

Could you advice?
Thanks
Khoa Nguyen

**Comment by khoait** [comment]
Hi,

It is actually because of hosting.json. I have to add `<Content Remove="hosting.json" />` in csproj file and delete the hosting.json of the previous deployment in the website folder using azure kudu dashboard.

You may want to add notes for the hosting.json in your course video.

Thanks
